-- Practical challenge lessons for BH-GRC-2, BH-SPEC-IAM, BH-SPEC-CLOUD, BH-SPEC-GRC.
-- One practical per module (16 total). Each contains a scenario and tasks.
-- Practicals use the same lessons table; title prefix "Practical:" distinguishes them in the UI.

BEGIN;

-- ========== Ensure the four courses exist (idempotent) ==========
INSERT INTO public.courses (id, code, title, description, level, required_tier_level, duration_hours, order_index, aligned_certifications) VALUES
  ('a0000000-0000-4000-8000-000000000008', 'BH-GRC-2',      'Practitioner Core: GRC',          'Governance, risk, and compliance.',          3, 2, 100, 5, ARRAY['ISC² SSCP']),
  ('a0000000-0000-4000-8000-000000000009', 'BH-SPEC-IAM',    'Specialisation: IAM',             'Identity and Access Management.',            4, 3, 120, 7, ARRAY['CISSP']),
  ('a0000000-0000-4000-8000-00000000000a', 'BH-SPEC-CLOUD',  'Specialisation: Cloud Security',  'Cloud security (AWS, Azure, GCP).',          4, 3, 120, 8, ARRAY['AWS Security','Microsoft SC-200']),
  ('a0000000-0000-4000-8000-00000000000b', 'BH-SPEC-GRC',    'Specialisation: Advanced GRC',    'Advanced governance, risk, and compliance.', 4, 3, 120, 9, ARRAY['CRISC'])
ON CONFLICT (code) DO NOTHING;

-- ========== Ensure all 16 modules exist (idempotent) ==========
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
  ('d0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000008', 'GRC Foundations',                          'Governance, risk, and compliance in the context of cybersecurity.', 1),
  ('d0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000008', 'Risk Management',                          'Identification, assessment, treatment, and monitoring of risk.',    2),
  ('d0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000008', 'Policy and Control Frameworks',            'Policies, standards, and common frameworks.',                      3),
  ('d0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000008', 'Compliance and Audit',                     'Compliance programmes, audits, and reporting.',                    4),
  ('d0000000-0000-4000-8000-000000000011', 'a0000000-0000-4000-8000-000000000009', 'IAM Fundamentals',                         'Identity, authentication, authorization, and directory services.', 1),
  ('d0000000-0000-4000-8000-000000000012', 'a0000000-0000-4000-8000-000000000009', 'Access Control Models and Mechanisms',     'DAC, MAC, RBAC, ABAC, MFA, and privileged access.',               2),
  ('d0000000-0000-4000-8000-000000000013', 'a0000000-0000-4000-8000-000000000009', 'Identity Lifecycle and Federation',        'Provisioning, deprovisioning, SSO, and federation.',              3),
  ('d0000000-0000-4000-8000-000000000014', 'a0000000-0000-4000-8000-000000000009', 'IAM in Practice',                          'Zero trust, cloud IAM, monitoring, and incident response.',       4),
  ('d0000000-0000-4000-8000-000000000021', 'a0000000-0000-4000-8000-00000000000a', 'Cloud Security Fundamentals',              'Shared responsibility, cloud models, and threats.',               1),
  ('d0000000-0000-4000-8000-000000000022', 'a0000000-0000-4000-8000-00000000000a', 'Cloud Identity and Access',                'IAM in cloud, roles, policies, conditional access.',              2),
  ('d0000000-0000-4000-8000-000000000023', 'a0000000-0000-4000-8000-00000000000a', 'Cloud Infrastructure and Network Security','VPC, encryption, logging, and hardening.',                        3),
  ('d0000000-0000-4000-8000-000000000024', 'a0000000-0000-4000-8000-00000000000a', 'Cloud Security Operations',                'CSPM, incident response, and compliance in cloud.',               4),
  ('d0000000-0000-4000-8000-000000000031', 'a0000000-0000-4000-8000-00000000000b', 'Enterprise Risk Management',               'ERM framework, risk appetite, and board-level risk.',             1),
  ('d0000000-0000-4000-8000-000000000032', 'a0000000-0000-4000-8000-00000000000b', 'IT Risk Identification and Analysis',      'IT-specific risk scenarios and quantitative methods.',            2),
  ('d0000000-0000-4000-8000-000000000033', 'a0000000-0000-4000-8000-00000000000b', 'Risk Response and Monitoring',             'Response strategies, KRIs, and risk reporting.',                  3),
  ('d0000000-0000-4000-8000-000000000034', 'a0000000-0000-4000-8000-00000000000b', 'Governance and Reporting',                 'Risk governance, committees, and assurance.',                     4)
ON CONFLICT (id) DO NOTHING;

-- ========== BH-GRC-2: PRACTICALS ==========
INSERT INTO public.lessons (id, module_id, title, description, content_markdown, duration_minutes, order_index) VALUES

-- Module 1: GRC Foundations
('f0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001',
 'Practical: Map the GRC Structure',
 'Apply governance, risk, and compliance concepts to a realistic organisational scenario.',
 E'# Practical: Map the GRC Structure\n\n## Scenario\n\nYou have just joined **FinSecure**, a 300-person financial services company, as a GRC analyst. Here is what you learn in your first week:\n\n- The **CEO** sets business strategy. The **CIO** oversees all IT. The **IT Security Manager** reports to the CIO and handles day-to-day security *and* risk assessments.\n- A **Head of Compliance** reports to the CFO and manages regulatory filings, but does not coordinate with the IT Security Manager.\n- Security policies were last reviewed two years ago. There is no formal risk committee.\n- The company processes customer payment data and stores personal information.\n\n## Tasks\n\n**Task 1 — Identify a governance gap.** Describe one structural problem in FinSecure''s setup and explain why it is a gap.\n\n**Task 2 — Risk register ownership.** Who should own the risk register: the CEO, the CIO, the Head of Compliance, or the IT Security Manager? Justify your answer in two sentences.\n\n**Task 3 — Compliance obligations.** List three compliance obligations FinSecure likely has, based on the description.\n\n**Task 4 — Explain GRC.** The CEO asks: "What is GRC in one sentence?" Write your answer as you would say it to a non-technical executive.', 25, 4),

-- Module 2: Risk Management
('f0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000002',
 'Practical: Build a Risk Register',
 'Identify, assess, and treat risks using a risk register for a realistic scenario.',
 E'# Practical: Build a Risk Register\n\n## Scenario\n\nYou are the GRC analyst at **ShopEasy**, an e-commerce company with 150 employees. The IT team has flagged these concerns:\n\n1. Several servers have not been patched in over 60 days.\n2. Customer support staff share one generic login to the CRM system.\n3. Backups run nightly but have never been tested for restore.\n4. A third-party payment processor recently suffered a publicised breach.\n5. Two former employees still have active VPN accounts.\n\n## Tasks\n\n**Task 1 — Write risk scenarios.** Pick any three of the five concerns. For each, write one risk scenario sentence in the format: *[Threat] exploits [vulnerability] to affect [asset], resulting in [impact].*\n\n**Task 2 — Assess each risk.** Use this 3x3 matrix to assign a likelihood (Rare / Possible / Likely) and impact (Low / Medium / High) to each of your three risks. State the resulting risk level.\n\n| | Low | Medium | High |\n|--|-----|--------|------|\n| **Likely** | Medium | High | Critical |\n| **Possible** | Low | Medium | High |\n| **Rare** | Low | Low | Medium |\n\n**Task 3 — Treat the highest risk.** For your highest-rated risk, choose a treatment (Accept / Mitigate / Transfer / Avoid) and write a treatment plan: action, owner, deadline.\n\n**Task 4 — One-sentence summary.** Write one sentence you would say to the CEO to summarise the most urgent finding.''t been patched in two months and are exposed to ransomware — I recommend we prioritise patching within the next two weeks."', 30, 4),

-- Module 3: Policy and Control Frameworks
('f0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000003',
 'Practical: Control Mapping Exercise',
 'Classify governance documents and map controls to a framework.',
 E'# Practical: Control Mapping Exercise\n\n## Scenario\n\nYour manager at **DataTrust**, a data analytics firm, asks you to help prepare for a NIST CSF alignment assessment. She gives you a list of documents and controls and asks you to organise them.\n\n## Tasks\n\n**Task 1 — Classify these statements.** For each, state whether it is a **Policy**, **Standard**, or **Procedure**.\n\n1. "The organisation shall protect all customer data from unauthorised access."\n2. "Passwords must be at least 14 characters with uppercase, lowercase, and a number."\n3. "To reset a user''s password: (1) Verify identity via manager email. (2) Generate a temporary password in the admin console. (3) Notify the user by phone."\n4. "All employees must complete security awareness training annually."\n5. "Encryption at rest must use AES-256 for all databases containing PII."\n\n**Task 2 — Map controls to NIST CSF.** Map each control below to the correct NIST CSF function (**Identify, Protect, Detect, Respond, Recover**).\n\n| Control | NIST CSF Function |\n|---------|-------------------|\n| Annual risk assessment | ? |\n| Firewall on network perimeter | ? |\n| SIEM monitoring and alerting | ? |\n| Incident response plan | ? |\n| Tested backup and restore | ? |\n| Security awareness training | ? |\n\n**Task 3 — Find the gap.** The following NIST CSF functions have controls mapped. Which function has the weakest coverage, and what control would you recommend adding?\n\nIdentify: risk assessment, asset inventory. Protect: firewall, MFA, training. Detect: SIEM. Respond: IR plan. Recover: backups.', 25, 4),

-- Module 4: Compliance and Audit
('f0000000-0000-4000-8000-000000000004', 'd0000000-0000-4000-8000-000000000004',
 'Practical: Prepare for Audit',
 'Gather evidence, respond to findings, and draft compliance metrics.',
 E'# Practical: Prepare for Audit\n\n## Scenario\n\n**MediCloud**, a health-tech startup, has an ISO 27001 surveillance audit in four weeks. You are the GRC analyst. The auditor has sent a preliminary list of three requirements they will examine:\n\n1. **A.8.1** — Asset management: Assets associated with information shall be identified and an inventory maintained.\n2. **A.9.2** — User access management: Access shall be provisioned and revoked in a timely manner.\n3. **A.12.4** — Logging and monitoring: Event logs shall be produced and kept.\n\nYou also received a finding from the last audit that is still open:\n\n> **Finding #17:** Access reviews are required quarterly but the last review was completed 7 months ago. Severity: Major.\n\n## Tasks\n\n**Task 1 — Evidence pack.** For each of the three requirements, name the **control** that satisfies it and the **evidence** you would provide to the auditor.\n\n| Requirement | Control | Evidence |\n|-------------|---------|----------|\n| A.8.1 Asset management | ? | ? |\n| A.9.2 User access management | ? | ? |\n| A.12.4 Logging and monitoring | ? | ? |\n\n**Task 2 — Respond to the finding.** Write a response to Finding #17: assign an owner, set a deadline, describe the remediation action, and state how you will prevent recurrence.\n\n**Task 3 — Compliance metrics.** Draft three metrics you would include in a monthly compliance status report for MediCloud''s management.', 30, 4);

-- ========== BH-SPEC-IAM: PRACTICALS ==========
INSERT INTO public.lessons (id, module_id, title, description, content_markdown, duration_minutes, order_index) VALUES

-- Module 1: IAM Fundamentals
('f0000000-0000-4000-8000-000000000011', 'd0000000-0000-4000-8000-000000000011',
 'Practical: Identity and Access Analysis',
 'Classify identity concepts and identify authentication weaknesses in a real scenario.',
 E'# Practical: Identity and Access Analysis\n\n## Scenario\n\n**TechFlow** is a SaaS company with 80 employees. During your first week as an IAM analyst, you observe:\n\n- Employees log in to the corporate portal with a username and password (no MFA).\n- The finance team shares one service account to access the accounting system.\n- A developer has both "Developer" and "Database Admin" roles because he set up the DB last year.\n- Contractors get the same Active Directory group as full-time employees.\n- The HR system is the source of truth for employee data, but IT provisions accounts manually via tickets.\n\n## Tasks\n\n**Task 1 — Classify.** For each item below, state whether it is an example of **Identity**, **Authentication**, or **Authorization**.\n\n1. Jane''s Active Directory account with her email, department, and role.\n2. Entering a password to log in to the portal.\n3. Jane can view invoices but cannot approve payments.\n4. A YubiKey hardware token used at login.\n5. The "Finance-Approver" group that grants payment approval rights.\n\n**Task 2 — Identify weaknesses.** List three IAM weaknesses from the scenario above and explain the risk each creates.\n\n**Task 3 — Recommend fixes.** For each weakness, recommend one specific fix.', 25, 4),

-- Module 2: Access Control Models and Mechanisms
('f0000000-0000-4000-8000-000000000012', 'd0000000-0000-4000-8000-000000000012',
 'Practical: Design an RBAC Model',
 'Design roles, assign permissions, and check for separation of duties.',
 E'# Practical: Design an RBAC Model\n\n## Scenario\n\n**GreenLeaf** is an environmental consultancy with four departments: **Consulting**, **Finance**, **HR**, and **IT**. They use an internal project management system. You are asked to design RBAC roles.\n\nBusiness rules:\n- Consultants create and edit project reports.\n- Finance staff view project reports (for billing) and manage invoices.\n- HR manages employee records and onboarding documents.\n- IT administers the system: user accounts, configuration, and backups.\n- **No single person should be able to both create an invoice and approve a payment** (separation of duties).\n- The CEO needs read-only access to everything.\n\n## Tasks\n\n**Task 1 — Define roles.** Create a role for each function. For each role, list the permissions (e.g. "Create project report", "View invoice").\n\n**Task 2 — Check SoD.** Does your design enforce the separation of duties rule? If not, adjust it.\n\n**Task 3 — Identify a limitation.** Describe one scenario where RBAC alone is not flexible enough and ABAC would be better.''s reports during business hours and from a managed device. RBAC gives them access to all project reports based on their role; ABAC could add conditions (project classification = government AND device = managed AND time = business hours) to restrict access dynamically.', 25, 4),

-- Module 3: Identity Lifecycle and Federation
('f0000000-0000-4000-8000-000000000013', 'd0000000-0000-4000-8000-000000000013',
 'Practical: Access Review and Offboarding',
 'Conduct a quarterly access review and handle an employee departure.',
 E'# Practical: Access Review and Offboarding\n\n## Scenario\n\nYou are running the quarterly access review at **BrightPath**, an ed-tech company. Your manager gives you a list of 8 accounts to review.\n\n| # | Name | Role | Department | Last Login | Notes |\n|---|------|------|------------|------------|-------|\n| 1 | Alice K. | Developer | Engineering | 2 days ago | Active; recently promoted to Lead |\n| 2 | Bob M. | Contractor | Marketing | 45 days ago | Contract ended last month |\n| 3 | Carol T. | Finance Analyst | Finance | 1 day ago | Transferred from HR 3 months ago |\n| 4 | svc-deploy | Service Account | Engineering | Continuous | Used by CI/CD pipeline |\n| 5 | Dave R. | IT Admin | IT | 5 days ago | Also has Finance-Viewer role |\n| 6 | Eve S. | Intern | Engineering | 90 days ago | Internship ended 60 days ago |\n| 7 | Frank W. | Sales Rep | Sales | 1 day ago | No issues noted |\n| 8 | admin-backup | Service Account | IT | Never (interactive) | Has full admin privileges |\n\n## Tasks\n\n**Task 1 — Access review decisions.** For each account, decide: **Keep** (no change), **Modify** (change permissions), or **Revoke** (disable/remove). Write one sentence of justification for each.\n\n**Task 2 — Offboarding checklist.** Bob (contractor) and Eve (intern) both need offboarding. Write the steps you would take for Bob, in order.\n\n**Task 3 — Flag a risk.** Which account is the highest risk? Why? What would you recommend?''s manager that all company assets (laptop, badge) are returned.\n7. Log the offboarding actions and date for audit.\n\n**Task 3:** Account #8 (admin-backup) — a service account with full admin privileges that has never been used interactively is a high-value target. If compromised, an attacker gets full admin. Recommendation: restrict to backup-only permissions (least privilege), vault the credential, enable logging, and set an alert for any interactive login attempt.', 30, 4),

-- Module 4: IAM in Practice
('f0000000-0000-4000-8000-000000000014', 'd0000000-0000-4000-8000-000000000014',
 'Practical: Respond to a Credential Compromise',
 'Investigate an identity alert and take containment and recovery actions.',
 E'# Practical: Respond to a Credential Compromise\n\n## Scenario\n\nAt 02:15 on a Tuesday, the SIEM at **CloudBridge** (a consulting firm) generates this alert:\n\n> **ALERT:** Admin account "j.admin" — 47 failed login attempts from IP 198.51.100.42 (Country: unknown) between 01:50 and 02:10, followed by 1 successful login at 02:12. MFA was not triggered. The account then performed: (1) Added a new user "support-temp" to the Domain Admins group at 02:14. (2) Downloaded 2.3 GB from the shared drive at 02:18.\n\nAdditional context:\n- j.admin is a domain administrator account used by the IT Director.\n- The IT Director is on leave this week.\n- MFA was configured but was recently disabled for j.admin "temporarily" during a system migration.\n\n## Tasks\n\n**Task 1 — First 5 actions.** List, in order, the first five things you would do upon seeing this alert.\n\n**Task 2 — Investigate lateral movement.** What would you check to determine if the attacker moved to other systems or accounts?\n\n**Task 3 — Root cause.** Based on the scenario, what is the most likely root cause of this compromise?\n\n**Task 4 — Incident summary.** Write a 4-sentence incident summary suitable for the CISO.''s session.\n- Review shared drive logs: what was downloaded? Is it sensitive or regulated data?\n- Check if the attacker created persistence (scheduled tasks, new services, additional credentials).\n\n**Task 3:** MFA was disabled for j.admin during the migration, leaving the account with password-only authentication. The attacker likely obtained the password (phishing, credential stuffing, or breach reuse) and brute-forced until successful. With no MFA, there was no second barrier.\n\n**Task 4:** "At 02:12 on Tuesday, the domain admin account j.admin was compromised after MFA was temporarily disabled, resulting in the creation of an unauthorised admin account and a 2.3 GB data download from the shared drive. We contained the incident by disabling the account, removing the rogue admin, and blocking the attacker IP within 15 minutes of detection. Root cause is the removal of MFA during a system migration. We recommend immediately re-enabling MFA for all admin accounts and investigating the downloaded data for sensitive content."', 30, 4);

-- ========== BH-SPEC-CLOUD: PRACTICALS ==========
INSERT INTO public.lessons (id, module_id, title, description, content_markdown, duration_minutes, order_index) VALUES

-- Module 1: Cloud Security Fundamentals
('f0000000-0000-4000-8000-000000000021', 'd0000000-0000-4000-8000-000000000021',
 'Practical: Shared Responsibility Worksheet',
 'Assign security responsibilities across IaaS, PaaS, and SaaS workloads.',
 E'# Practical: Shared Responsibility Worksheet\n\n## Scenario\n\n**NovaTech** is migrating three workloads to the cloud:\n\n1. **Web servers** — Moving to IaaS virtual machines (e.g. EC2 / Azure VM).\n2. **Application database** — Moving to a PaaS managed database (e.g. RDS / Azure SQL).\n3. **Corporate email** — Moving to SaaS (e.g. Microsoft 365 / Google Workspace).\n\n## Tasks\n\n**Task 1 — Assign responsibilities.** For each workload and each security area, mark **Provider** or **Customer**.\n\n| Security Area | Web Servers (IaaS) | Database (PaaS) | Email (SaaS) |\n|---------------|--------------------|-----------------|--------------|\n| Physical datacentre security | ? | ? | ? |\n| Operating system patching | ? | ? | ? |\n| Network firewall / security groups | ? | ? | ? |\n| Data encryption at rest | ? | ? | ? |\n| Identity and access management | ? | ? | ? |\n| Data classification and handling | ? | ? | ? |\n\n**Task 2 — Biggest risk.** For each workload, identify the single biggest customer-side risk (i.e. what is most likely to go wrong on the customer''s side).\n\n**Task 3 — One control per risk.** For each risk in Task 2, name one control the customer should implement.', 25, 4),

-- Module 2: Cloud Identity and Access
('f0000000-0000-4000-8000-000000000022', 'd0000000-0000-4000-8000-000000000022',
 'Practical: Review a Cloud IAM Policy',
 'Find least-privilege violations in a policy and write a corrected version.',
 E'# Practical: Review a Cloud IAM Policy\n\n## Scenario\n\nA developer at **StreamData** submitted this IAM policy for a Lambda function that reads customer orders from an S3 bucket and writes logs to CloudWatch:\n\n```\n{\n  "Version": "2012-10-17",\n  "Statement": [\n    {\n      "Effect": "Allow",\n      "Action": "s3:*",\n      "Resource": "*"\n    },\n    {\n      "Effect": "Allow",\n      "Action": "logs:*",\n      "Resource": "*"\n    },\n    {\n      "Effect": "Allow",\n      "Action": "iam:*",\n      "Resource": "*"\n    }\n  ]\n}\n```\n\n## Tasks\n\n**Task 1 — Find violations.** Identify at least three least-privilege violations in this policy.\n\n**Task 2 — Write a corrected policy.** Rewrite the policy so it grants only what the Lambda function needs. Use specific actions and resources.\n\n**Task 3 — Conditional access.** If you could add one condition to further restrict this policy, what would it be and why?', 25, 4),

-- Module 3: Cloud Infrastructure and Network Security
('f0000000-0000-4000-8000-000000000023', 'd0000000-0000-4000-8000-000000000023',
 'Practical: Design Cloud Network Security',
 'Assign subnets and write security group rules for a 3-tier application.',
 E'# Practical: Design Cloud Network Security\n\n## Scenario\n\n**PayRight** is deploying a payment processing application in the cloud with three tiers:\n\n1. **Web tier** — Load balancer serving HTTPS to the public internet.\n2. **App tier** — Application servers that process payments (not internet-facing).\n3. **Data tier** — PostgreSQL database holding transaction records (not internet-facing).\n\nAdmins access the app tier via SSH from a management VPN (IP range: 10.0.100.0/24).\n\n## Tasks\n\n**Task 1 — Subnet design.** Assign each tier to a subnet type (**public** or **private**). Explain why.\n\n**Task 2 — Security group rules.** Write the inbound rules for each tier''s security group. Use this format:\n\n| Tier | Protocol | Port | Source | Purpose |\n|------|----------|------|--------|---------|\n\n**Task 3 — Spot the mistake.** A colleague proposes adding this rule to the data tier: "Allow TCP 5432 from 0.0.0.0/0." What is wrong and what should it be instead?', 25, 4),

-- Module 4: Cloud Security Operations
('f0000000-0000-4000-8000-000000000024', 'd0000000-0000-4000-8000-000000000024',
 'Practical: Cloud Incident Triage',
 'Prioritise CSPM findings and respond to a cloud security alert.',
 E'# Practical: Cloud Incident Triage\n\n## Scenario\n\nYou are the cloud security analyst at **AeroStack**. Monday morning, your CSPM dashboard shows these five findings:\n\n| # | Finding | Severity |\n|---|---------|----------|\n| 1 | S3 bucket "aerostack-public-assets" has public read access | Medium |\n| 2 | Root account used for console login yesterday; no MFA | Critical |\n| 3 | EC2 instance in prod has port 22 (SSH) open to 0.0.0.0/0 | High |\n| 4 | CloudTrail logging is disabled in eu-west-1 region | High |\n| 5 | IAM user "dev-test" has access keys that have not been rotated in 400 days | Medium |\n\nSimultaneously, you receive this CloudTrail alert:\n\n> **02:47 UTC:** IAM user "dev-test" called `CreateUser` and `AttachUserPolicy` (AdministratorAccess) from IP 203.0.113.55. This user has never performed IAM actions before.\n\n## Tasks\n\n**Task 1 — Prioritise CSPM findings.** Rank the five findings from most urgent to least. Justify your top pick.\n\n**Task 2 — Respond to the alert.** The CloudTrail alert indicates possible compromise of dev-test. List your first five containment actions.\n\n**Task 3 — Post-incident improvement.** After containment, name two controls you would implement to prevent this from happening again.''s access keys immediately.\n2. Delete or disable the newly created user and remove AdministratorAccess.\n3. Block IP 203.0.113.55 at the firewall / WAF.\n4. Check CloudTrail for any other actions by dev-test or from that IP (new resources, data access, persistence).\n5. Preserve CloudTrail logs; snapshot any affected resources for investigation.\n\n**Task 3:**\n1. Enforce mandatory key rotation policy (e.g. 90 days maximum) with automated alerts for overdue keys.\n2. Apply a service control policy (SCP) or IAM permission boundary that prevents IAM users from creating other users or attaching admin policies unless from an approved admin role.', 30, 4);

-- ========== BH-SPEC-GRC (Advanced GRC): PRACTICALS ==========
INSERT INTO public.lessons (id, module_id, title, description, content_markdown, duration_minutes, order_index) VALUES

-- Module 1: Enterprise Risk Management
('f0000000-0000-4000-8000-000000000031', 'd0000000-0000-4000-8000-000000000031',
 'Practical: Enterprise Risk Heat Map',
 'Place risks on a heat map and present IT risk alongside enterprise risk.',
 E'# Practical: Enterprise Risk Heat Map\n\n## Scenario\n\n**GlobalParts**, a manufacturing company, has identified these eight enterprise risks:\n\n| # | Risk | Category | Likelihood | Impact |\n|---|------|----------|------------|--------|\n| 1 | Ransomware disrupts production line | IT/Cyber | Likely | Critical |\n| 2 | Key supplier goes bankrupt | Supply chain | Possible | High |\n| 3 | New regulation increases compliance cost | Regulatory | Likely | Medium |\n| 4 | Data breach of employee PII | IT/Cyber | Possible | High |\n| 5 | Factory fire | Operational | Rare | Critical |\n| 6 | Currency fluctuation affects margins | Financial | Likely | Medium |\n| 7 | Insider steals trade secrets | IT/Cyber | Rare | High |\n| 8 | Product recall due to defect | Operational | Possible | Critical |\n\n## Tasks\n\n**Task 1 — Heat map.** Place each risk on this matrix by writing its number in the correct cell.\n\n| | Medium Impact | High Impact | Critical Impact |\n|--|---------------|-------------|------------------|\n| **Likely** | ? | ? | ? |\n| **Possible** | ? | ? | ? |\n| **Rare** | ? | ? | ? |\n\n**Task 2 — Top 3.** Identify the top three risks. For each, state whether it should be escalated to the board and why.\n\n**Task 3 — Integration.** The CRO says: "IT risks should be in a separate report." Write a 3-sentence argument for why IT/cyber risks should be on the same heat map as all other enterprise risks.', 25, 4),

-- Module 2: IT Risk Identification and Analysis
('f0000000-0000-4000-8000-000000000032', 'd0000000-0000-4000-8000-000000000032',
 'Practical: Quantitative Risk Assessment',
 'Calculate ALE, compare controls, and build a business case.',
 E'# Practical: Quantitative Risk Assessment\n\n## Scenario\n\nThe CISO at **LogiFreight** (a logistics company) asks you to build a business case for two proposed controls. You have this data:\n\n**Risk A — Ransomware on dispatch system:**\n- Estimated cost per incident (SLE): $400,000\n- Estimated frequency: once every 4 years (ARO: 0.25)\n- Proposed control: Advanced endpoint detection + backup hardening. Annual cost: $35,000. Expected to reduce ARO to 0.05.\n\n**Risk B — Data breach via compromised vendor portal:**\n- Estimated cost per incident (SLE): $250,000\n- Estimated frequency: once every 5 years (ARO: 0.20)\n- Proposed control: Vendor portal MFA + network segmentation. Annual cost: $12,000. Expected to reduce ARO to 0.04.\n\n## Tasks\n\n**Task 1 — Calculate.** For each risk, calculate:\n- Current ALE (before control)\n- New ALE (after control)\n- ALE reduction\n- Net benefit (ALE reduction minus control cost)\n\n**Task 2 — Recommend.** Which control(s) should be funded? Justify with the numbers.\n\n**Task 3 — Business case.** Write a 3-sentence summary for the CISO recommending the investment.', 30, 4),

-- Module 3: Risk Response and Monitoring
('f0000000-0000-4000-8000-000000000033', 'd0000000-0000-4000-8000-000000000033',
 'Practical: KRI Dashboard Design',
 'Define KRIs with thresholds and build a risk monitoring dashboard.',
 E'# Practical: KRI Dashboard Design\n\n## Scenario\n\nThe new CISO at **SecureEdge** (a cybersecurity consultancy) wants a risk dashboard. She has identified these top five risks:\n\n1. Ransomware — disruption to internal systems.\n2. Client data breach — loss of client confidential data.\n3. Insider threat — employee misuse of access.\n4. Third-party compromise — vendor with access to systems is breached.\n5. Compliance failure — missed regulatory deadline or failed audit.\n\n## Tasks\n\n**Task 1 — Define KRIs.** For each of the five risks, define one KRI. For each KRI, state:\n- **Metric** (what is measured)\n- **Green** threshold (acceptable)\n- **Amber** threshold (watch)\n- **Red** threshold (escalate)\n- **Data source** (where the number comes from)\n\n**Task 2 — Action on red.** Pick any two KRIs. For each, describe what action should be taken when the KRI turns red.\n\n**Task 3 — Reporting.** The CISO wants to show this dashboard to the board quarterly. In two sentences, explain how you would present it.', 25, 4),

-- Module 4: Governance and Reporting
('f0000000-0000-4000-8000-000000000034', 'd0000000-0000-4000-8000-000000000034',
 'Practical: Draft a Board Risk Report',
 'Produce a board-ready risk report from given data.',
 E'# Practical: Draft a Board Risk Report\n\n## Scenario\n\nYou are the risk analyst at **UrbanGrid** (an energy utility). The quarterly board meeting is in three days. Your manager gives you this data and asks you to draft the risk section of the board pack.\n\n**Data provided:**\n- **Risk register:** 22 risks total; 2 critical, 5 high, 10 medium, 5 low. The 2 critical risks are: (a) Ransomware on SCADA systems (Likely + Critical; treatment: segmentation + backups, 60% complete), (b) Regulatory non-compliance with new energy data rules (Likely + High, upgraded to Critical due to deadline in 90 days; treatment: gap assessment underway, 30% complete).\n- **KRIs:** 3 green, 1 amber (patch compliance at 88%, target 95%), 1 red (vendor assessments overdue — 2 critical vendors not assessed in 12 months).\n- **Audit:** Internal audit completed review of access controls; 3 findings (1 major: service accounts with standing admin access; 2 minor). Remediation plan accepted.\n- **Incidents:** 1 phishing incident contained; no data loss.\n\n## Tasks\n\n**Task 1 — Executive summary.** Write a 3–4 sentence executive summary for the board.\n\n**Task 2 — Top risks.** Present the two critical risks in a format suitable for the board (risk, level, treatment status, ask).\n\n**Task 3 — Decision needed.** State one decision or resource request the board should make based on this data.\n\n**Task 4 — KRI highlight.** The vendor assessment KRI is red. Write two sentences explaining this to the board and what is being done.', 30, 4);

COMMIT;
